### ISSUE TITLE
Extension Meta Data Not Being Saved

### ISSUE THREAD

**Issue by lewisSkyline** [woocommerce/wceu23-shipping-workshop-final#3]
Hello,

I've tried modifying this plugin and also just using it 'as-is' but the Meta data doesn't seem to be saving.

When inspecting the network request for the checkout, I can see the extension data there - but it isn't being saved to the meta data for the order.

The first issue I'm facing seems to be that the 'woocommerce_store_api_checkout_update_order_from_request' isn't being hooked into properly when it sits within the 'initialize' function. Moving this hook to the main plugin file seems to be a quick fix for this.

However, when it is in the plugin file, the $request object seems to be missing extension data. I've logged $request->body, and can see the extension data there - but when trying to access the body params e.g $request->get_body_params() - it seems to have everything other than extensions (extensions is just an empty array).

Perhaps I'm missing a key step here, but I've not been able to find it as of yet. Are there any known issues or is this still working ok for others? Happy to share system reports. 

Thanks
Lewis

**Comment by opr** [comment]
Hey @lewisSkyline thanks for trying out our tutorial code!

I'll take a look into this and get back to you with some more information. In the meantime would you be able to upload your code (attach a zip to this issue) or send a link to a repo with it in?

**Comment by lewisSkyline** [comment]
Hi @opr - thank you for coming back to me.

I've attached a zip containing the plugin exactly as it is sitting on our test site - hopefully it is something simple that I've missed during the build process or upload. (This is the copy of the tutorial taken directly from this repo). I'm hoping if I can spot the issue in this then I'll be able to fix the issue on the modified version that I've been working on.

I've also attached a system report just showing that there isn't really anything else installed.
[shipping-workshop.zip](https://github.com/woocommerce/wceu23-shipping-workshop-final/files/13438041/shipping-workshop.zip)
[woo-system-report.txt](https://github.com/woocommerce/wceu23-shipping-workshop-final/files/13438042/woo-system-report.txt)

Let me know if you need any other information or if there is anything I should try in the meantime.

Thanks

**Comment by opr** [comment]
Hey @lewisSkyline thanks for sharing this.

We made a change to how block registration is handled, and it's no longer done on Store API requests, which is why this code isn't working.

I'm going to update this example code and the template code thanks to your report! I'll tag you in the PR if you'd like to test that.

**Comment by lewisSkyline** [comment]
Hello @opr 

Downloaded your updated code and tested on a development site and it is working as expected now.

Thank you for the update!
