### ISSUE TITLE
Translations not loading

### ISSUE THREAD

**Issue by fabiocorreia95** [woocommerce/wceu23-shipping-workshop-final#6]
First of all, thank you for sharing this guide.

I replicated the project following the workshop video and I can't get translations working. Cloning this project also does not apply the defined translations.

I'm using the plugin "Loco Translate" to set translations.

Is there something I'm missing or are the translations not functioning properly?

Thank you.

**Comment by opr** [comment]
Hi @fabiocorreia95 thanks for your feedback, I actually didn't have translations in mind when working on this. I just checked and you're right, they're not working using Loco Translate, thanks for reporting that.

I'll add this to our backlog to be looked at but it's not likely to be addressed as a high priority. Any updates will be added to this issue.

**Comment by fabiocorreia95** [comment]
Hello,

I have one more question, if it's not too much trouble.

What is the suggested way to add translations without the "Loco Translate" plugin?
I tried using WP-CLI ([wp i18n command](https://developer.wordpress.org/cli/commands/i18n/)) to create the translation files and all strings were successfully detected (in the .pot file). I also created the files with the translations (.po files). However, they are not loaded either.

Thank you very much for the answer and help.

**Comment by opr** [comment]
Hi @fabiocorreia95 I think you'd need to load the translations on the front-end too, here's [some documentation I found about i18n](https://learn.wordpress.org/tutorial/common-apis-internationalization/) - hopefully it can point you in the right direction!
